### ISSUE TITLE
Time only pair throwing TypeError when end time before start time

### ISSUE THREAD

**Issue by jamesnowek** [jonthornton/Datepair.js#31]
"TypeError: endDate.getTime is not a function (Datepair.js:273)"
is thrown on the first selection of an end time that is before the start time for a datepair that is only times.

http://jsfiddle.net/Jameopotato/61bhaum4/4/

Reproduce the error by running the fiddle and selecting an endtime of 8am. Since the default duration is 9hrs the start time will default to 11pm. This should throw the error described.

**Comment by jonthornton** [comment]
Thanks for taking the time to report this!

**Comment by acoard** [comment]
This bug seems to have come back in v0.4.7.

While Googling this problem I found this thread.  When I overwrite my datepair.js with the `dist/datepair.js` file referenced in the above commit the problem was fixed.

[Source code that works](https://github.com/jonthornton/Datepair.js/blob/4eecc8006eb0c9434756b87ddd28f1bd3edc0780/dist/datepair.js)

Thanks for the lib!

**Comment by jonthornton** [comment]
I don't see it in the latest version, 0.4.13. If you're still seeing the error, could you post instructions to reproduce?

**Comment by acoard** [comment]
I hadn't tested on 0.4.13, only on 0.4.7. Didn't realize I was on such an out of date version, I only started the project recently.

I'll tested on 0.4.13 tonight and make sure it still works.

Thanks!
